# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
    authors:
      - 
  categories:
    - title: Project Plan
      labels:
        - project-plan
    - title: Software Quality Assurance Plan
      labels:
        - sqap
    - title: Software Requirements Specification
      labels:
        - srs
    - title: System Architecture Design and Research Report
      labels:
        - sadrr
    - title: Detailed Design and Implementation Report
      labels:
        - design
    - title: Team Leader and Client Liaison
      labels:
        - 
    - title: Development Manager and Planning Manager
      labels:
        - 
    - title: Support Manager and Developer
      labels:
        - 
        - 
    - title: Quality Manager and Developer
      labels:
        - 
        - 
    - title: Dropped
      labels:
        - invalid
        - wontfix
    - title: Other Changes
      labels:
        - "*"
