version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000" # Map port 5000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
