blank_issues_enabled: true
contact_links:
  - name: Computing Technology Project A Discussions
    url: https://github.com/elyithium/ctpa/discussions
    about: "Please make a Discussion, Issues can be created from Discussions."
